# Generated by Django 4.2 on 2026-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='昵称')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统用户',
                'db_table': 'sys_user',
            },
        ),
    ]
