# Generated by Django 4.2 on 2026-07-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='password',
            field=models.CharField(default='123456', max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='username',
            field=models.CharField(default='admin', max_length=30, unique=True, verbose_name='账号'),
        ),
    ]
